// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccEjalhjw0jqcRCkFcFv64eF2J43-LqQ',
    appId: '1:490112069267:web:a0ee47d589e67c29a7a766',
    messagingSenderId: '490112069267',
    projectId: 'project-9c798064-4761-45ee-873',
    authDomain: 'project-9c798064-4761-45ee-873.firebaseapp.com',
    storageBucket: 'project-9c798064-4761-45ee-873.firebasestorage.app',
    measurementId: 'G-9K7X4FXDYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMPiQL_A5IFN49Zn7CKrVhpVEeq51bAA',
    appId: '1:490112069267:android:7e4397218e0f2fcaa7a766',
    messagingSenderId: '490112069267',
    projectId: 'project-9c798064-4761-45ee-873',
    storageBucket: 'project-9c798064-4761-45ee-873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATUChjCf4Na2NJftTL891YMCaIg3wDQg8',
    appId: '1:490112069267:ios:1d9314f9add4d32aa7a766',
    messagingSenderId: '490112069267',
    projectId: 'project-9c798064-4761-45ee-873',
    storageBucket: 'project-9c798064-4761-45ee-873.firebasestorage.app',
    iosBundleId: 'com.example.projectIti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATUChjCf4Na2NJftTL891YMCaIg3wDQg8',
    appId: '1:490112069267:ios:1d9314f9add4d32aa7a766',
    messagingSenderId: '490112069267',
    projectId: 'project-9c798064-4761-45ee-873',
    storageBucket: 'project-9c798064-4761-45ee-873.firebasestorage.app',
    iosBundleId: 'com.example.projectIti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCccEjalhjw0jqcRCkFcFv64eF2J43-LqQ',
    appId: '1:490112069267:web:ee03de183ad9e5dda7a766',
    messagingSenderId: '490112069267',
    projectId: 'project-9c798064-4761-45ee-873',
    authDomain: 'project-9c798064-4761-45ee-873.firebaseapp.com',
    storageBucket: 'project-9c798064-4761-45ee-873.firebasestorage.app',
    measurementId: 'G-NG1SVVLZ9H',
  );
}
